spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/inventorydb-t2
    password: vw@22*CF!11
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
